{
 "title": "NGINX Metrics",
 "description": "NGINX metrics with Prometheus based on https://github.com/martin-helmich/prometheus-nginxlog-exporter Based on namespace prefix 'nginx'. If different, you may need to adjust the metrics.Dashboard based on 6482 dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(nginx_http_response_count_total,app)"
    }
   },
   { "name": "percentiles", "label": "Latency Percentiles", "query": "99, 90, 50" },
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values(nginx_http_response_count_total{app=~\"$app\"},method)"
    }
   },
   {
    "name": "path",
    "label": "Path",
    "query": {
     "query": "label_values(nginx_http_response_count_total{app=~\"$app\"},path)"
    }
   },
   {
    "name": "status",
    "label": "Status Code",
    "query": {
     "query": "label_values(nginx_http_response_count_total{app=~\"$app\"},status)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Response Code Breakdown",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(nginx_http_response_count_total{status=~\"^2..\", app=~\"$app\", method=~\"$method\", path=~\"$path\"}[$__range])) > 0) / (sum(increase(nginx_http_response_count_total{app=~\"$app\", method=~\"$method\", path=~\"$path\"}[$__range])) > 0) * 100",
     "legendFormat": "2xx status codes"
    },
    {
     "expr": "(sum(increase(nginx_http_response_count_total{status=~\"^3..\", app=~\"$app\", method=~\"$method\", path=~\"$path\"}[$__range])) > 0) / (sum(increase(nginx_http_response_count_total{app=~\"$app\", method=~\"$method\", path=~\"$path\"}[$__range])) > 0) * 100 ",
     "legendFormat": "3xx status codes"
    },
    {
     "expr": "(sum(increase(nginx_http_response_count_total{status=~\"^4..\", app=~\"$app\", method=~\"$method\", path=~\"$path\"}[$__range])) > 0) / (sum(increase(nginx_http_response_count_total{app=~\"$app\", method=~\"$method\", path=~\"$path\"}[$__range])) > 0) * 100 ",
     "legendFormat": "4xx status codes"
    },
    {
     "expr": "(sum(increase(nginx_http_response_count_total{status=~\"^5..\", app=~\"$app\", method=~\"$method\", path=~\"$path\"}[$__range])) > 0) / (sum(increase(nginx_http_response_count_total{app=~\"$app\", method=~\"$method\", path=~\"$path\"}[$__range])) > 0) * 100",
     "legendFormat": "5xx status codes"
    }
   ]
  },
  { "title": "Request Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Per-endpoint Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (app, method, path)(rate(nginx_http_response_time_seconds_count{app=~\"$app\", method=~\"$method\", path=~\"$path\", status=~\"$status\"}[$__rate_interval])) > 0",
     "legendFormat": "{{ app }} - {{ method }} {{ path }}"
    }
   ]
  },
  {
   "title": "Overall Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (app)(rate(nginx_http_response_time_seconds_count{app=~\"$app\", method=~\"$method\", path=~\"$path\", status=~\"$status\"}[$__rate_interval])) > 0",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  { "title": "Response Codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Per-endpoint Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_count_total{app=~\"$app\", method=~\"$method\", path=~\"$path\", status=~\"$status\"}[$__rate_interval])) by (app, method, path, status) > 0",
     "legendFormat": "{{app}} - {{method }} {{ path }} {{ status }}"
    }
   ]
  },
  {
   "title": "Overall Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_count_total{app=~\"$app\", method=~\"$method\", path=~\"$path\", status=~\"$status\"}[$__rate_interval])) by (app, status) > 0",
     "legendFormat": "{{app}} - {{ status }}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Per-endpoint Latency P$percentiles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "repeat": "percentiles",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentiles, sum by (app, method, path, le)(rate(nginx_http_response_time_seconds_hist_bucket{app=~\"$app\", method=~\"$method\", path=~\"$path\", status=~\"$status\"}[$__rate_interval]))) > 0",
     "legendFormat": "{{ app }} - {{ method }} {{ path }}"
    }
   ]
  },
  {
   "title": "Overall Latency P$percentiles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "repeat": "percentiles",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentiles, sum by (app, le)(rate(nginx_http_response_time_seconds_hist_bucket{app=~\"$app\", method=~\"$method\", path=~\"$path\", status=~\"$status\"}[$__rate_interval]))) > 0",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Per-endpoint Bandwidth",
   "type": "timeseries",
   "description": "Request/Response sizes in bytes",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (app, method, path)(rate(nginx_http_request_size_bytes{app=~\"$app\", method=~\"$method\", path=~\"$path\", status=~\"$status\"}[$__rate_interval])) > 0",
     "legendFormat": "{{ app }} - {{ method }} {{ path }} Request"
    },
    {
     "expr": "sum by (app, method, path)(rate(nginx_http_response_size_bytes{app=~\"$app\", method=~\"$method\", path=~\"$path\", status=~\"$status\"}[$__rate_interval])) > 0",
     "legendFormat": "{{ app }} - {{ method }} {{ path }} Response"
    }
   ]
  },
  {
   "title": "Overall Bandwidth",
   "type": "timeseries",
   "description": "Request/Response sizes in bytes",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (app)(rate(nginx_http_request_size_bytes{app=~\"$app\", method=~\"$method\", path=~\"$path\", status=~\"$status\"}[$__rate_interval])) > 0",
     "legendFormat": "{{ app }} - Request"
    },
    {
     "expr": "sum by (app)(rate(nginx_http_response_size_bytes{app=~\"$app\", method=~\"$method\", path=~\"$path\", status=~\"$status\"}[$__rate_interval])) > 0",
     "legendFormat": "{{ app }} - Response"
    }
   ]
  }
 ]
}