global:
  scrape_interval: 30s
  evaluation_interval: 60s

scrape_configs:
  {%- for job, port in scrape_jobs.items() %}
  - job_name: {{ job }}
    static_configs:
      - targets:
          - {{ metrics_host }}:{{ port }}
  {% endfor %}
