base:
  "*":
    - packages
    - users
    - oh-my-zsh
    - openssh
    - openssh.config
    - remove-pi
    - motd
    - build-tools
    - git-access
    - grafana
    - mongo
    - postgres
    - prometheus
    - rabbitmq
    - nginx
    - secrets
    - hashbash
    - stupidchess
    - nginx-log-exporters
