app_secret_key: !IncludeText
  filename: !JoinFilePaths
    - !EnvVar SECRETS_VOLUME_PATH
    - flask-app-secret-key

MONGODB_SETTINGS:
  - host: {{ mongo_host }}
    db: stupidchess
    authentication_source: stupidchess
    username: stupidchess-rw
    password: !IncludeText
      filename: !JoinFilePaths
        - !EnvVar SECRETS_VOLUME_PATH
        - mongo-password
