{
 "title": "NGINX Metrics",
 "description": "NGINX metrics with Prometheus based on https://github.com/martin-helmich/prometheus-nginxlog-exporter Based on namespace prefix 'nginx'. If different, you may need to adjust the metrics.Dashboard based on 6482 dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(nginx_http_response_count_total,app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Response Code Breakdown",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_count_total{status=~\"^2..\", app=~\"$app\"}[$__rate_interval])) / sum(rate(nginx_http_response_count_total{app=~\"$app\"}[$__rate_interval])) * 100",
     "legendFormat": "2** status codes"
    },
    {
     "expr": "sum(rate(nginx_http_response_count_total{status=~\"^4..\", app=~\"$app\"}[$__rate_interval])) / sum(rate(nginx_http_response_count_total{app=~\"$app\"}[$__rate_interval])) * 100",
     "legendFormat": "4** status codes"
    },
    {
     "expr": "sum(rate(nginx_http_response_count_total{status=~\"^5..\", app=~\"$app\"}[$__rate_interval])) / sum(rate(nginx_http_response_count_total{app=~\"$app\"}[$__rate_interval])) * 100",
     "legendFormat": "5** status codes"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (app)(rate(nginx_http_response_time_seconds_count{app=~\"$app\"}[$__rate_interval])) ",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Response Time P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (app, method, path, le)(rate(nginx_http_response_time_seconds_hist_bucket{app=~\"$app\"}[$__rate_interval])))",
     "legendFormat": "{{ app }} - {{ method }} {{ path }}"
    }
   ]
  },
  {
   "title": "HTTP Traffic Size",
   "type": "timeseries",
   "description": "Request/Response sizes in bytes",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (app)(rate(nginx_http_request_size_bytes{app=~\"$app\"}[$__rate_interval])) ",
     "legendFormat": "{{ app }} - Request"
    },
    {
     "expr": "sum by (app)(rate(nginx_http_response_size_bytes{app=~\"$app\"}[$__rate_interval])) ",
     "legendFormat": "{{ app }} - Response"
    }
   ]
  },
  {
   "title": "Response Time P50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (app, method, path, le)(rate(nginx_http_response_time_seconds_hist_bucket{app=~\"$app\"}[$__rate_interval])))",
     "legendFormat": "{{ app }} - {{method }} {{ path }}"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_response_count_total{app=~\"$app\"}[$__rate_interval])) by (app, status)",
     "legendFormat": "{{app}} - {{ status }}"
    }
   ]
  }
 ]
}