global:
  scrape_interval: 30s
  evaluation_interval: 60s

scrape_configs:
  # node-exporters for each raspberry pi in the cluster
  - job_name: rpi-nodes
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: cloudflared
    static_configs:
      - targets:
          - tunnel:2323

  - job_name: hashbash-engine
    metrics_path: /metrics
    static_configs:
      - targets:
          - hashbash:8082

  - job_name: hashbash-webapp
    metrics_path: /metrics
    static_configs:
      - targets:
          - hashbash:8081

  # prometheus server itself
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  # mongodb-exporter
  - job_name: mongodb
    static_configs:
      - targets:
          - mongodb:9001

  # postgres-exporter
  - job_name: postgresql
    static_configs:
      - targets:
          - postgres:9187
