global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  # node-exporters for each raspberry pi in the cluster
  - job_name: rpi-nodes
    static_configs:
      - targets:
          - 0p0:9100
          - 0s0:9100
          - 0s1:9100
          - 0s2:9100

  # hashbash-engine
  - job_name: hashbash-engine
    metrics_path: /prometheus
    static_configs:
      - targets:
          - 0p0:8082
          - 0s0:8082
          - 0s1:8082
          - 0s2:8082

  # hashbash-webapp
  - job_name: hashbash-webapp
    metrics_path: /prometheus
    static_configs:
      - targets:
          - 0s0:8081
          - 0s1:8081
          - 0s2:8081

  # hashbash-nginx-exporter
  - job_name: hashbash-nginx
    static_configs:
      - targets:
          - 0s0:4041
          - 0s1:4041
          - 0s2:4041

  # stupidchess-nginx-exporter
  - job_name: stupidchess-nginx
    static_configs:
      - targets:
          - 0s0:4040
          - 0s1:4040
          - 0s2:4040

  # prometheus server
  - job_name: prometheus
    static_configs:
      - targets:
          - 0p0:9090

  # mongodb-exporter
  - job_name: mongodb
    static_configs:
      - targets:
          - 0p0:9001

  # postgres-exporter
  - job_name: postgresql
    static_configs:
      - targets:
          - 0p0:9187
