global:
  scrape_interval: 30s
  evaluation_interval: 60s

scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets:
          - {{ metrics_host }}:{{ ports.node_exporter }}

  - job_name: process-exporter
    static_configs:
      - targets:
          - {{ metrics_host }}:{{ ports.process_exporter }}

  - job_name: cloudflared
    static_configs:
      - targets:
          - {{ metrics_host }}:{{ ports.tunnel_metrics }}

  - job_name: hashbash-engine
    metrics_path: /metrics
    static_configs:
      - targets:
          - {{ metrics_host }}:{{ ports.hashbash_engine_metrics }}

  - job_name: hashbash-webapp
    metrics_path: /metrics
    static_configs:
      - targets:
          - {{ metrics_host }}:{{ ports.hashbash_webapp_metrics }}

  # prometheus server itself
  - job_name: prometheus
    static_configs:
      - targets:
          - {{ metrics_host }}:{{ ports.prometheus }}

  # mongodb-exporter
  - job_name: mongodb
    static_configs:
      - targets:
          - {{ metrics_host }}:{{ ports.mongodb_exporter }}

  # postgres-exporter
  - job_name: postgresql
    static_configs:
      - targets:
          - {{ metrics_host }}:{{ ports.postgres_exporter }}

  # rabbitmq-exporter
  - job_name: rabbitmq
    static_configs:
      - targets:
          - {{ metrics_host }}:{{ ports.rabbitmq_metrics }}
