global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  # prometheus server
  - job_name: prometheus
    static_configs:
      - targets:
          - rp4-sma-git-mon-sql-000:9090

  # node-exporters for each raspberry pi in the cluster
  - job_name: rpi-nodes
    static_configs:
      - targets:
          - rp4-sma-git-mon-sql-000:9100
          - rp3-smi-elb-000:9100
          - rp3-smi-mdb-000:9100
          - rp3-smi-rmq-000:9100

  # mongodb-exporter
  - job_name: mongodb
    static_configs:
      - targets:
          - rp3-smi-mdb-000:9001

  # postgres-exporter
  - job_name: postgresql
    static_configs:
      - targets:
          - rp4-sma-git-mon-sql-000:9187

  # hashbash-engine
  - job_name: hashbash-engine
    metrics_path: /prometheus
    static_configs:
      - targets:
          - rp4-sma-git-mon-sql-000:8082
          - rp3-smi-elb-000:8082
          - rp3-smi-mdb-000:8082
          - rp3-smi-rmq-000:8082

  # hashbash-webapp
  - job_name: hashbash-webapp
    metrics_path: /prometheus
    static_configs:
      - targets:
          - rp4-sma-git-mon-sql-000:8081
          - rp3-smi-elb-000:8081
          - rp3-smi-mdb-000:8081
          - rp3-smi-rmq-000:8081

  # hashbash-nginx-exporter
  - job_name: hashbash-nginx
    static_configs:
      - targets:
          - rp4-sma-git-mon-sql-000:4041
          - rp3-smi-elb-000:4041
          - rp3-smi-mdb-000:4041
          - rp3-smi-rmq-000:4041

  # stupidchess-nginx-exporter
  - job_name: stupidchess-nginx
    static_configs:
      - targets:
          - rp4-sma-git-mon-sql-000:4040
          - rp3-smi-elb-000:4040
          - rp3-smi-mdb-000:4040
          - rp3-smi-rmq-000:4040
