base:
  "*":
    - swapfile
    - packages
    - users
    - remove-default-users
    - network
    - oh-my-zsh
    - build-tools
    - go
    - node
    - rust
    - dns
    - nginx
    - node-exporter
    - nginx-log-exporter
    - process-exporter
    - prometheus
    - grafana
    - mongo
    - postgres
    - rabbitmq
    - bolas
    - hashbash
    - stupidchess
    - rpi-loadbalancer
    - tunnels
